version: '3.8'

services:
  viruela_mono_api:
    image: donovanvincelara/viruela_mono_api:latest
    container_name: viruela_mono_api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo_new
    networks:
      - app-network
    environment:
      PORT: 3000
      MONGO_URL: mongodb://root:root@mongo_new:27017/

  mongo_new:
    image: mongo
    container_name: mongo_new
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db
    networks:
      - app-network

volumes:
  mongodb_volume:

networks:
  app-network: