version: '3.8'

services:
  virus-mono:
    build: .
    container_name: virus-mono
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URL: mongodb://root:root@mongo_bdd:27017/
    depends_on:
      - mongo_db
    networks:
      - app-network

  mongo_db:
    image: mongo
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - mongodb_volume:/data/db
    networks:
      - app-network

volumes:
  mongodb_volume:

networks:
  app-network: