name: Docker Build & Publish

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build Docker image
        run: docker build -t donovanvincelara/viruela_mono_api:${{ github.sha }} .

      - name: Tag Latest
        run: docker tag donovanvincelara/viruela_mono_api:${{ github.sha }} donovanvincelara/viruela_mono_api:latest

      - name: Push Docker image
        run: | 
          docker push donovanvincelara/viruela_mono_api:${{ github.sha }}
          docker push donovanvincelara/viruela_mono_api:latest